Repository Dirnei/node-red-contrib-zigbee2mqtt-devices, pull requests merged in 2020-11, with the labels that each got.

#40 Fixed OTA node
  README.MD
  package.json
  src/non-z2m-nodes/mqtt-config.js
  src/zigbee2mqtt-config.js
Labels: bug

#47 makes sure devices are listed if node-red has httpAdminRoot configured
  src/devices-hue.html
  src/devices-ikea.html
  src/devices-scenic.html
  src/devices-sonoff.html
  src/devices-tint.html
  src/ota.html
  src/scenes.html
  src/sensors.html
  src/zigbee2mqtt-config.html
  src/zigbee2mqtt.html
Labels: enhancement

#44 Added new Ikea Dimmer node (v2)
  lib/outputHandler.js
  lib/utils.js
  src/_api.js
  src/devices-ikea.html
  src/devices-ikea.js
  src/zigbee2mqtt.js
Labels: enhancement, new device

#53 fixed bug when brightness was a empty string, and simplyfied send-messages node
  lib/utils.js
  src/zigbee2mqtt.js
Labels: bug

#56 fixed wrong property name
  src/zigbee2mqtt.js
Labels: bug

#59 Output handler docstrings
  lib/outputHandler.js
Labels: enhancement

#57 Added the bridge log node
  README.MD
  docs/nodes/bridge-log.md
  docs/nodes/img/bridge-log-config-consolidate-output.png
  docs/nodes/img/bridge-log-config.png
  docs/nodes/img/bridge-log-flow-consolidate-output.png
  docs/nodes/img/bridge-log-flow.png
  package.json
  src/bridge-log.html
  src/bridge-log.js
  upcomming-changelog.md
Labels: enhancement
