Repository Dirnei/node-red-contrib-zigbee2mqtt-devices, pull requests merged in 2021-01, with the labels that each got.

#64 Feature/typescript
  .github/workflows/node.js-ci.yml
  .gitignore
  .npmignore
  .vscode/tasks.json
  _template.js
  install.ps1
  package-lock.json
  package.json
  src/_api.html
  src/_api.js
  src/bridge-log.js
  src/lib/outputHandler.js
  src/lib/utils.js
  src/nodes/devices-eurotronic.html
  src/nodes/devices-eurotronic.js
  src/nodes/devices-ikea.html
  src/nodes/devices-ikea.js
  src/nodes/devices-scenic.html
  src/nodes/devices-scenic.js
  src/nodes/devices-sonoff.html
  src/nodes/devices-sonoff.js
  src/nodes/devices-tasmota.html
  src/nodes/devices-tasmota.js
  src/nodes/devices-tint.html
  src/nodes/devices-tint.js
  src/nodes/hue-dimmer/devices-hue.html
  src/nodes/hue-dimmer/devices-hue.js
  src/nodes/override/override-nodes.html
  src/nodes/override/override-nodes.ts
  src/nodes/override/types.ts
  src/nodes/scenes.html
  src/nodes/scenes.js
  src/nodes/sensors.html
  src/nodes/sensors.js
  src/non-z2m-nodes/devices-shelly-25.js
  src/non-z2m-nodes/mqtt-config.ts
  src/ota.js
  src/override-nodes.js
  src/types.ts
  src/zigbee2mqtt-config.html
  src/zigbee2mqtt-config.ts
  src/zigbee2mqtt.js
  tsconfig.json
  upcomming-changelog.md
Labels: needs testing

#65 Removed custom MQTT client
  README.MD
  docs/config/bridge-config.md
  docs/config/img/bridge-config-config.png
  docs/config/img/mqtt-config-config.png
  docs/config/mqtt-config.md
  docs/img/overview.png
  resources/logo.svg
  src/_api.js
  src/device-types.ts
  src/lib/mqtt.ts
  src/nodes/devices-eurotronic.js
  src/nodes/devices-ikea.js
  src/nodes/devices-scenic.js
  src/nodes/devices-sonoff.js
  src/nodes/devices-tint.js
  src/nodes/hue-dimmer/devices-hue.js
  src/nodes/sensors.js
  src/non-z2m-nodes/mqtt-config.html
  src/non-z2m-nodes/mqtt-config.ts
  src/types.ts
  src/zigbee2mqtt-config.html
  src/zigbee2mqtt-config.ts
  src/zigbee2mqtt.html
  src/zigbee2mqtt.js
  upcomming-changelog.md
Labels: bug, enhancement

#70 Unified device-selection
  src/_api.html
  src/_api.js
  src/nodes/devices-eurotronic.html
  src/nodes/devices-ikea.html
  src/nodes/devices-scenic.html
  src/nodes/devices-sonoff.html
  src/nodes/devices-tint.html
  src/nodes/hue-dimmer/devices-hue.html
  src/zigbee2mqtt-config.html
  src/zigbee2mqtt-config.ts
  src/zigbee2mqtt.html
  upcomming-changelog.md
Labels: enhancement

#78 Switched generic sensor nodes to new device-selection
  src/nodes/sensors.html
  upcomming-changelog.md
Labels: enhancement

#79 improved device filter
  src/_api.js
  src/nodes/devices-eurotronic.html
  src/nodes/sensors.html
  upcomming-changelog.md
Labels: enhancement

#85 Feature/documentation overview
  .npmignore
  README.MD
  docs/changelog.md
  docs/config/bridge-config.md
  docs/config/device-config.md
  docs/config/mqtt-config.md
  docs/documentation.md
  docs/getting-started.md
  docs/img/getting-started-flow13-on-off-flow-3.gif
  docs/nodes/bridge-log.md
  docs/nodes/button-switch.md
  docs/nodes/device-status.md
  docs/nodes/generic-lamp.md
  docs/nodes/get-lamp-state.md
  docs/nodes/img/ota-node-example-flow-over-night.png
  docs/nodes/ota-node.md
  docs/nodes/override-action.md
  docs/nodes/override-brightness.md
  docs/nodes/override-color.md
  docs/nodes/override-nodes.md
  docs/nodes/override-state.md
  docs/nodes/override-temperature.md
  docs/nodes/scene-in.md
  docs/nodes/scene-selector.md
  docs/nodes/send-messages.md
  examples/getting-started/one-lamp-on-off.json
  examples/getting-started/two-lamps-override.json
  upcomming-changelog.md
Labels: documentation

#86 Fix/device selection
  src/_api.html
  src/_api.js
  upcomming-changelog.md
Labels: enhancement

#87 climate-sensor enhancement
  README.MD
  docs/documentation.md
  docs/nodes/climate-sensor.md
  docs/nodes/img/climate-sensor-config.png
  package.json
  src/nodes/sensors.html
  src/nodes/sensors.js
  upcomming-changelog.md
Labels: enhancement

#89 Remove eslintrc, dashboard and resources from the package
  .npmignore
  upcoming-changelog.md
Labels: enhancement

#90 Updated fallback checks for old ikea dimmer
  src/nodes/devices-ikea.js
  upcoming-changelog.md
Labels: bug

#92 Ikea v2 remote filter broken MQTT messages
  src/nodes/devices-ikea.js
Labels: bug
